--- 
title: "Undergraduate Practical Course for Psychology"
author: "psyTeachR"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: An overview of our undergraduate practical Teaching in Psychology using R and the Tidyverse for reproducible data analysis and open educational practices and in our pedadogical approach
---


# Introduction

This book presents an overview of our undergraduate practical Teaching in Psychology using R and the Tidyverse for reproducible data analysis and open educational practices to teachong practical skills methodology.  We highlight briefly what we have done and give some practical example that can be adapted to different teaching settings.  We then link to resources in the different parts of our curriculum and assessment.

If you want to skip ahead to the content for differnet resources, here are some quick links:
  UG Level 1
  UG Level 2
  UG Level 3
  webex R Package for making exercises
  assessr R Package for making and marking assessments

## Who we are

We are a growing team of teachers in the School of Psychology and the Institute of Neuroscience and Psychology at the University of Glasgow who collectively call ourselves #PsyTeachR.  We have lead the way in changing teaching of analysis practical skills in our undergraduate and postgraduate programmes since 2014.

## About this Book

This book gives an overview of our approach for Undergraduat teaching.  It is a living document and will change as we add more resources.  

Sections include:

How to get started
Pedadogical Approach
Practical Teaching for L1
Practical Teaching for L2
Practical Teaching for L3
Exercises
Assessment
Evaluation of the approach

## Call-out Blocks

```{block, type="danger"}
Note dangerous things that will break code.
```

```{block, type="warning"}
Warn readers.
```

```{block, type="info"}
Give further information.
```

```{block, type="try"}
Stop and try something.
```



```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown'
), 'packages.bib')
```

